### ISSUE TITLE
Remote Browser: Wrong Directory with similiar name

### ISSUE THREAD

**Issue by demimontalto** [liximomo/vscode-sftp#570]
Hello, I'm having a weird issue with the remote browser.

I have two sub folder in wordpress and they are called like this:

- wp-content
    - themes
        - Divi
        - Divi Child Theme

Basically, if I try to access 'Divi Child Theme', it shows me 'Divi' folder files
Is this a real or I'm just doing it wrong?

**Comment by liximomo** [comment]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run command '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
