### ISSUE TITLE
sync delete local to remote 

### ISSUE THREAD

**Issue by mediasale** [liximomo/vscode-sftp#573]
**descprition**
sync delete local to remote  not working

**resove problem method**

    "syncOption": {
        "update": true,
        "delete": true
    },
    "syncMode": "full",

**Comment by liximomo** [comment]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run command '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by zmj1368** [comment]
helpful!

**Comment by nathan0066** [comment]
helpful!

**Comment by Synicix** [comment]
How is this not fixed yet :(

Thanks though, the suggested fix it works just fine.

**Comment by thesagarmahajan** [comment]
> **descprition**
> sync delete local to remote not working
> 
> **resove problem method**
> 
> ```
> "syncOption": {
>     "update": true,
>     "delete": true
> },
> "syncMode": "full",
> ```

**### Perfectly Worked for me!!! Thanks!!**
