### ISSUE TITLE
SFTP loading icon

### ISSUE THREAD

**Issue by rj-45** [liximomo/vscode-sftp#583]
The plugin works great connects fine upload files no problem then every so often when going to upload a file it seems to get stuck 

Bottom left I have SFTP and the animated squares any ideas? this is the same on both laptop and pc

VS Code 1.35.1
SFTP v 1.12.7

**Comment by liximomo** [comment]
**Do you read the FAQ?**
- [ ] Yes.
- [ ] [I am going to read now.](https://github.com/liximomo/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run command '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
