### ISSUE TITLE
sftp.json of vscode-sftp upload github.com will lead to information(ex: host ,user, password, ) leaks!

### ISSUE THREAD

**Issue by MrTheWhiteHat** [liximomo/vscode-sftp#77]
## Expected Behavior
[Description of the expected behavior]

## Actual Behavior
[Description of the actual behavior]

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Extension Logs
  [set option `sftp.printDebugLog` to true, then reload vscode, reproduce the problem, get the logs(view -> output-> sftp)]
 

## Specifications

  - Version:
  - Platform:

**Comment by twn346** [comment]
This is not an issue with this extension; it is an issue with ANY sftp type of plugin where the settings file can be in the same folder as the repository. The solution is simple: Don't add the settings file to the repository.

Feasible methods to use this plugin and not add your sensitive information to the repo:
1) add the sftp.json file to the (either machine-local or repository) .gitignore file.
1) Use one sftp.json file for all of your repositories in a parent folder above all of your repositories, and use the multi-config approach. This way, the file is never inside of a repository in the first place.

If you're still worried about the passwords being stored in the file, use the `agent` parameter in the settings file with an SSH key so that you don't need to store the passwords in the config file at all.
